# Generated by Django 3.2.9 on 2021-11-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='alias',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='hero',
            name='name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
